name: 07 - Using Expressions
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: github.event_name == 'push'
              run: |
               echo "Triggered ${{ github.event_name }}"
               echo "Branch: ${{ github.ref }}"
               echo "Commit SHA: ${{ github.SHA }}"
               echo "Runner OS: ${{ github.OS }}"
            - name: '[debug] Print when triggered from main'
              run: echo "I was triggered from main"
            - name: Greeting
              run: echo "Hello, world"          
                


